site_name: DeepTS_Forecasting
site_url: http://yunxileo.github.io/deepts_forecasting
repo_url: https://github.com/yunxileo/deepts_forecasting
repo_name: deepts_forecasting
#strict: true
nav:
  - home: index.md
  - installation: installation.md
  - usage: usage.md
  - modules: api.md
  - API: reference/
  - contributing: contributing.md
  - authors: authors.md
  - history: history.md
theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    primary: light blue
  features:
    - navigation.indexes
    - navigation.tabs
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      # emoji_index: !!python/name:materialx.emoji.twemoji
      # emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
      slugify: !!python/name:pymdownx.slugs.uslugify
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          import:
          - https://docs.python.org/3/objects.inv
          selection:
            docstring_style: google
            docstring_options:
              ignore_init_summary: yes
          rendering:
            show_submodules: no
            docstring_section_style: list
            members_order: alphabetical
            show_category_heading: no
            merge_init_into_class: yes
      watch:
        - deepts_forecasting
extra:
  social:
    - icon: fontawesome/brands/twitter
      # replace with your own tweet link below
      link: http://www.jieyu.ai
      name: Tweet
    - icon: fontawesome/brands/facebook
      # replace with your own facebook link below
      link: http://www.jieyu.ai
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/yunxileo/deepts_forecasting
      name: Github
    - icon: material/email
      link: "mailto:weiwillstat@163.com"
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
